# models generated by sqlacodegen --generator sqlmodel
from datetime import datetime, timedelta
from typing import Optional
from uuid import UUID, uuid4

from sqlalchemy import (
    BigInteger,
    Boolean,
    Column,
    DateTime,
    Double,
    Integer,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import INTERVAL, JSONB
from sqlmodel import Field, Relationship, SQLModel


class WildCamerasAnnotationlabel(SQLModel, table=True):
    __tablename__ = "wild_cameras_annotationlabel"

    id: int | None = Field(
        default=None,
        primary_key=True,
    )
    text_: str = Field(sa_column=Column("text", String(150)))
    blur: bool = Field(sa_column=Column("blur", Boolean))


class WildCamerasImage(SQLModel, table=True):
    __tablename__ = "wild_cameras_image"

    id: int | None = Field(
        default=None,
        primary_key=True,
    )
    uuid: UUID = Field(default_factory=uuid4)
    dataset_id: int = Field(
        foreign_key="wild_cameras_dataset.id",
    )
    hidden: bool = Field(sa_column=Column("hidden", Boolean))
    sequence_index: int = Field(sa_column=Column("sequence_index", Integer))
    captured_at: datetime | None = Field(
        default=None, sa_column=Column("captured_at", DateTime(True))
    )
    metadata_: dict | None = Field(default={}, sa_column=Column("metadata", JSONB))
    timeseries_id: int | None = Field(
        default=None, foreign_key="wild_cameras_timeseries.id"
    )
    file: str | None = Field(default=None, sa_column=Column("file", String(100)))
    classified_at: datetime | None = Field(
        default=None, sa_column=Column("classified_at", DateTime(True))
    )
    ext_id: str | None = Field(default=None)
    dataset: Optional["WildCamerasDataset"] = Relationship(back_populates="images")
    bboxes: list["WildCamerasBboxannotation"] = Relationship(back_populates="image")
    timeseries: Optional["WildCamerasTimeseries"] = Relationship(
        back_populates="images",
        sa_relationship_kwargs={"foreign_keys": "WildCamerasImage.timeseries_id"},
    )
    selected_image_in_timeseries: Optional["WildCamerasTimeseries"] = Relationship(
        back_populates="selected_image",
        sa_relationship_kwargs={
            "uselist": False,
            "foreign_keys": "WildCamerasTimeseries.selected_image_id",
        },
    )


class WildCamerasTimeseries(SQLModel, table=True):
    __tablename__ = "wild_cameras_timeseries"

    id: int | None = Field(
        default=None,
        primary_key=True,
    )
    created_at: datetime = Field(sa_column=Column("created_at", DateTime(True)))
    last_modified_at: datetime = Field(
        sa_column=Column("last_modified_at", DateTime(True))
    )
    extra: dict = Field(sa_column=Column("extra", JSONB))
    dataset_id: int = Field(foreign_key="wild_cameras_dataset.id")
    hidden: bool = Field(sa_column=Column("hidden", Boolean))
    comment: str | None = Field(default=None, sa_column=Column("comment", Text))
    predicted_species_id: int | None = Field(
        default=None, sa_column=Column("predicted_species_id", BigInteger)
    )
    selected_image_id: int | None = Field(
        default=None, foreign_key="wild_cameras_image.id"
    )
    validated_species_id: int | None = Field(
        default=None, sa_column=Column("validated_species_id", BigInteger)
    )
    ext_id: str | None = Field(default=None)

    selected_image: Optional["WildCamerasImage"] = Relationship(
        back_populates="selected_image_in_timeseries",
        sa_relationship_kwargs={
            "foreign_keys": "WildCamerasTimeseries.selected_image_id",
        },
    )
    images: list["WildCamerasImage"] = Relationship(
        back_populates="timeseries",
        sa_relationship_kwargs={"foreign_keys": "WildCamerasImage.timeseries_id"},
    )
    dataset: "WildCamerasDataset" = Relationship(back_populates="timeseries")
    revisions: list["WildCamerasValidationrevision"] = Relationship(
        back_populates="timeseries"
    )


class WildCamerasBboxannotation(SQLModel, table=True):
    __tablename__ = "wild_cameras_bboxannotation"

    id: int | None = Field(
        default=None,
        primary_key=True,
    )
    created_at: datetime = Field(sa_column=Column("created_at", DateTime(True)))
    image_id: int = Field(foreign_key="wild_cameras_image.id")
    label_id: int = Field(sa_column=Column("label_id", BigInteger))
    user_id: int = Field(sa_column=Column("user_id", BigInteger))
    x_min: float | None = Field(default=None, sa_column=Column("x_min", Double(53)))
    x_max: float | None = Field(default=None, sa_column=Column("x_max", Double(53)))
    y_min: float | None = Field(default=None, sa_column=Column("y_min", Double(53)))
    y_max: float | None = Field(default=None, sa_column=Column("y_max", Double(53)))
    score: float | None = Field(default=None, sa_column=Column("score", Double(53)))
    ext_id: str | None = Field(default=None)

    image: WildCamerasImage = Relationship(back_populates="bboxes")


class WildCamerasValidationrevision(SQLModel, table=True):
    __tablename__ = "wild_cameras_validationrevision"

    id: int | None = Field(
        default=None,
        primary_key=True,
    )
    created_at: datetime = Field(sa_column=Column("created_at", DateTime(True)))
    last_modified_at: datetime = Field(
        sa_column=Column("last_modified_at", DateTime(True))
    )
    user_id: int = Field(sa_column=Column("user_id", BigInteger))
    comment: str | None = Field(default=None, sa_column=Column("comment", Text))
    label_id: int | None = Field(default=None, sa_column=Column("label_id", BigInteger))
    timeseries_id: int | None = Field(
        default=None, foreign_key="wild_cameras_timeseries.id"
    )

    timeseries: "WildCamerasTimeseries" = Relationship(back_populates="revisions")


class WildCamerasLocation(SQLModel, table=True):
    __tablename__ = "wild_cameras_location"

    id: int | None = Field(
        default=None,
        sa_column=Column("id", BigInteger, primary_key=True),
    )
    created_at: datetime = Field()
    last_modified_at: datetime = Field()
    comment: str | None = Field(default="")
    original_sr: int = Field(default=4326)

    datasets: list["WildCamerasDataset"] = Relationship(back_populates="location")


class WildCamerasDataset(SQLModel, table=True):
    __tablename__ = "wild_cameras_dataset"

    id: int | None = Field(
        default=None,
        primary_key=True,
    )
    created_at: datetime = Field(sa_column=Column("created_at", DateTime(True)))
    last_modified_at: datetime = Field(
        sa_column=Column("last_modified_at", DateTime(True))
    )
    deleted: bool = Field(sa_column=Column("deleted", Boolean))
    location_id: int = Field(
        foreign_key="wild_cameras_location.id",
    )
    locked: bool = Field(sa_column=Column("locked", Boolean))
    comment: str | None = Field(default=None, sa_column=Column("comment", Text))
    registration_id: int | None = Field(
        default=None, sa_column=Column("registration_id", BigInteger)
    )
    delta: timedelta | None = Field(default=None, sa_column=Column("delta", INTERVAL))
    ext_id: str | None = Field(default=None)

    location: WildCamerasLocation | None = Relationship(back_populates="datasets")
    images: list[WildCamerasImage] = Relationship(back_populates="dataset")
    timeseries: list[WildCamerasTimeseries] = Relationship(back_populates="dataset")
